#! /bin/bash

if [ ! -f "${HOME}/Desktop/winegui.desktop" ]; then
  cp /usr/share/applications/winegui.desktop "${HOME}/Desktop/"
fi

touch "${HOME}/.config/panel-reload"
gio mime inode/directory caja-browser.desktop

winegui
